# Generated by Django 5.1.5 on 2025-01-28 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='place_of_work',
            field=models.ForeignKey(blank=True, help_text='Укажите ИП или организацию сотрудником, которой вы являетесь', null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.partner', verbose_name='Место работы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, help_text='Укажите вашу страну', max_length=100, null=True, verbose_name='Страна'),
        ),
    ]
