# Generated by Django 5.1.5 on 2025-01-28 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('factory', 'завод'), ('retail chain', 'розничная сеть'), ('individual entrepreneur', 'индивидуальный предприниматель')], default='retail chain', help_text='Выберите тип партнера', max_length=23, verbose_name='Тип партнера')),
                ('name', models.CharField(help_text='Введите имя организации или ИП', max_length=300, verbose_name='Имя партнера')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
        migrations.CreateModel(
            name='PartnerContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Укажите электронную почту', max_length=254, unique=True, verbose_name='Электронная почта')),
                ('country', models.CharField(help_text='Укажите страну', max_length=100, verbose_name='Страна')),
                ('city', models.CharField(help_text='Укажите ваш город', max_length=200, verbose_name='Город')),
                ('street', models.CharField(help_text='Укажите улицу', max_length=100, verbose_name='Улица')),
                ('building_number', models.CharField(help_text='Укажите номер дома', max_length=10, verbose_name='Номер дома')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('partner', models.ForeignKey(help_text='Укажите для какого партнера контакты', on_delete=django.db.models.deletion.CASCADE, to='partners.partner', verbose_name='Партнер')),
            ],
            options={
                'verbose_name': 'Контакты партнера',
                'verbose_name_plural': 'Контакты партнеров',
            },
        ),
    ]
