# Generated by Django 5.1.5 on 2025-02-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('factory', 'завод'), ('retail chain', 'розничная сеть'), ('individual entrepreneur', 'индивидуальный предприниматель')], default='retail chain', help_text='Выберите тип партнера', max_length=23, verbose_name='Тип партнера')),
                ('name', models.CharField(help_text='Введите имя организации или ИП', max_length=300, verbose_name='Имя партнера')),
                ('email', models.EmailField(help_text='Укажите электронную почту', max_length=254, verbose_name='Электронная почта')),
                ('country', models.CharField(help_text='Укажите страну', max_length=100, verbose_name='Страна')),
                ('city', models.CharField(help_text='Укажите ваш город', max_length=200, verbose_name='Город')),
                ('street', models.CharField(help_text='Укажите улицу', max_length=100, verbose_name='Улица')),
                ('building_number', models.CharField(help_text='Укажите номер дома', max_length=10, verbose_name='Номер дома')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания (записи в БД)')),
                ('amount_credit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Задолженность перед поставщиком')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название продукта', max_length=300, verbose_name='Название продукта')),
                ('model', models.CharField(blank=True, help_text='Введите модель продукта', max_length=150, null=True, verbose_name='Модель продукта')),
                ('launch_date', models.DateField(help_text='Введите дату выхода продукта на рынок в формате ГГГГ-ММ-ДД', verbose_name='Дата выхода продукта на рынок')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
