# Generated by Django 5.1.5 on 2025-01-31 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='partner',
            name='provider',
            field=models.ForeignKey(help_text='Укажите поставщика', null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.partner', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='credit',
            name='creditor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditor', to='partners.partner', verbose_name='Кредитор'),
        ),
        migrations.AddField(
            model_name='credit',
            name='debtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debtor', to='partners.partner', verbose_name='Дебитор'),
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.partner'),
        ),
    ]
